export type IconNames =
  | "search"
  | "monitoring"
  | "bell"
  | "filter"
  | "home"
  | "chart-pie"
  | "three-people"
  | "calendar"
  | "chart-graph"
  | "written-page"
  | "heart"
  | "settings"
  | "two-people"
  | "logout"
  | "gluco-guide"
  | "rotated-arrow"
  | "fire"
  | "heart-organ"
  | "human"
  | "weight-machine"
  | "up-arrow"
  | "right-arrow"
  | "human-jogging"
  | "human-cycling"
  | "soup-bowl"
  | "capsule-pill"
  | "tablet-pill"
  | "human-yoga"
  | "heart-w-pulse"
  | "beat-graphics"
  | "doctor"
  | "edit-icon"
  | "watch"
  | "cross"
  | "information"
  | "pin"
  | "chevron-right"
  | "simple-left-arrow"
  | "simple-right-arrow"

export type AppointmentCreationProps = {
  doctor: string
  appointmentMode: string
  purposeOfVisit: string[]
  selectedDate: Date
  selectedMonth: string
  selectedMonthDays: Date[]
  notes: string
  availableDays: string[]
  time: string
}
