export type IconNames =
  | "search"
  | "bell"
  | "home"
  | "chart-pie"
  | "three-people"
  | "calender"
  | "chart-graph"
  | "written-page"
  | "heart"
  | "settings"
  | "two-people"
  | "logout"
  | "gluco-guide"
